LT-21672: Add styles to table cells
sillsdev/FieldWorks pull request #17
Opened 2024-03-27 16:55 UTC by mark-sil

This adds support for when a style is applied to a specific cell or when different styles are applied to different pieces of the text in a cell.

Note: The changes in SetRunStyle() also add support for styles that are applied to all or a portion of the text in other fields (notes, custom fields …).

Change-Id: Id1ca7ccfaeaad7e7ea7e781263151b1714d9d90f

2024-03-27 18:51 UTC, jasonleenaylor requested changes
> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/17)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @aror92 and @mark-sil)

___
*[`Src/xWorks/ConfiguredLcmGenerator.cs` line 2811 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/17#-Nu0EJDI4f3mCRnrf_Qd:-Nu0EJDI4f3mCRnrf_Qe:bftfmgp) ([raw file](https://github.com/sillsdev/FieldWorks/blob/9dd6df0ee80168bc831beb98456cff7787630454/Src/xWorks/ConfiguredLcmGenerator.cs#L2811)):*
> ```Smalltalk
> 				var css = cssStyle.ToString();
> 
> 				settings.ContentGenerator.SetRunStyle(writer, config, writingSystem, css, style);
> ```

I think a different refactoring might be better here. What if instead of directly calling the CssGenerator here we use the settings.StyleGenerator and pass that in. css should be renamed style in the interface, and the writing system is still necessary for word, but it would unify the design here.



_Code quote:_
```Smalltalk
				var cssStyle = CssGenerator.GenerateCssStyleFromLcmStyleSheet(style,
					settings.Cache.WritingSystemFactory.GetWsFromStr(writingSystem), settings.PropertyTable);
				var css = cssStyle.ToString();

				settings.ContentGenerator.SetRunStyle(writer, config, writingSystem, css, style);
```


<!-- Sent from Reviewable.io -->

2024-03-27 19:44 UTC, mark-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/17)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @aror92 and @jasonleenaylor)

___
*[`Src/xWorks/ConfiguredLcmGenerator.cs` line 2811 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/17#-Nu0EJDI4f3mCRnrf_Qd:-Nu0Q3LM9juD4OBYPVZP:b-py43cl) ([raw file](https://github.com/sillsdev/FieldWorks/blob/9dd6df0ee80168bc831beb98456cff7787630454/Src/xWorks/ConfiguredLcmGenerator.cs#L2811)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

I think a different refactoring might be better here. What if instead of directly calling the CssGenerator here we use the settings.StyleGenerator and pass that in. css should be renamed style in the interface, and the writing system is still necessary for word, but it would unify the design here.
</blockquote></details>

Hi Jason, I don't understand what you are recommending.  How should settings.StylesGenerator be used?  I'm not sure if this is relevant, but the 'config' doesn't contain the style that we want.


<!-- Sent from Reviewable.io -->

2024-03-27 20:49 UTC, jasonleenaylor commented
*[`Src/xWorks/ConfiguredLcmGenerator.cs` line 2811 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/17#-Nu0EJDI4f3mCRnrf_Qd:-Nu0aR-nEljNpkv-jpll:b-f2ko4u) ([raw file](https://github.com/sillsdev/FieldWorks/blob/9dd6df0ee80168bc831beb98456cff7787630454/Src/xWorks/ConfiguredLcmGenerator.cs#L2811)):*
<details><summary><i>Previously, mark-sil (Mark Kidder) wrote…</i></summary><blockquote>

Hi Jason, I don't understand what you are recommending.  How should settings.StylesGenerator be used?  I'm not sure if this is relevant, but the 'config' doesn't contain the style that we want.
</blockquote></details>

After our chat in slack the new plan is to make sure that we are handling the export specific code in the right class. So in this case moving the css generating into the xhtml export is the change. Getting the ILcmStylesGenerator to handle this wasn't the best route.


<!-- Sent from Reviewable.io -->

2024-04-02 14:21 UTC, mark-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/17)* status: 3 of 5 files reviewed, all discussions resolved (waiting on @aror92)

___
*[`Src/xWorks/ConfiguredLcmGenerator.cs` line 2811 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/17#-Nu0EJDI4f3mCRnrf_Qd:-NuUAeGD5ZKL5krXdmKs:b-988cka) ([raw file](https://github.com/sillsdev/FieldWorks/blob/3911d717e7851c72d9c8604db061ef7ec980f63c/Src/xWorks/ConfiguredLcmGenerator.cs#L2811)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

After our chat in slack the new plan is to make sure that we are handling the export specific code in the right class. So in this case moving the css generating into the xhtml export is the change. Getting the ILcmStylesGenerator to handle this wasn't the best route.
</blockquote></details>

I’m not sure how to proceed with this.  Should I add an ‘error’ parameter to SetRunStyle() and keying off of that in the xhtml generator to create the css for large red text?


<!-- Sent from Reviewable.io -->

2024-04-04 18:49 UTC, jasonleenaylor approved these changes
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/17)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aror92)



<!-- Sent from Reviewable.io -->

2024-04-04 18:55 UTC, merged