LT-21706: Modify webonary status reporting
sillsdev/FieldWorks pull request #187
Opened 2024-10-23 21:13 UTC by jasonleenaylor

![image](https://github.com/user-attachments/assets/b2395a85-6e4b-400b-89d7-a52ea61ba57a)
![image](https://github.com/user-attachments/assets/f2df31b5-9d01-49a1-9396-7bf4346edc04)
![image](https://github.com/user-attachments/assets/aa8b8f3c-b9ed-44e4-9649-a928afcf79bd)

2024-10-28 21:04 UTC, JakeOliver28 requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/187)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @jasonleenaylor)

___
*[`Src/xWorks/UploadToWebonaryController.cs` line 157 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/187#-OAJujIl399QpOBi5p5k:-OAJujIm2M59KvutQXxG:bu3jg4u) ([raw file](https://github.com/sillsdev/FieldWorks/blob/8c87915626ccd44eecbb2e2acef2c981fc7a48d9/Src/xWorks/UploadToWebonaryController.cs#L157)):*
> ```Smalltalk
> 		{
> 			// if the file is an image file, check for a license file
> 			if (file.EndsWith(".jpg", StringComparison.InvariantCultureIgnoreCase) ||
> ```

Could we consolidate this?



_Code snippet:_
```Smalltalk
var imageExtensions = new HashSet<string>(StringComparer.InvariantCultureIgnoreCase)
{
	".jpg", ".jpeg", ".gif", ".png"
};

if (imageExtensions.Contains(Path.GetExtension(file))
{
	
}
```


<!-- Sent from Reviewable.io -->

2024-10-29 02:45 UTC, hahn-kev commented on Src/xWorks/UploadToWebonaryDlg.cs
> +			m_uploadStatus = (WebonaryStatusCondition)Enum.ToObject(typeof(WebonaryStatusCondition),
why the call `Enum.ToObject` instead of just casting the result of Math.Max directly to the enum? I can't see any functional difference

2024-10-29 15:59 UTC, JakeOliver28 requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/187)* status: 0 of 13 files reviewed, 3 unresolved discussions (waiting on @hahn-kev and @jasonleenaylor)

___
*[`Src/xWorks/WebonaryLogViewer.cs` line 60 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/187#-OAO-7-Y6Q3_1xOEDrVu:-OAO-7-Y6Q3_1xOEDrVv:b-inoq1h) ([raw file](https://github.com/sillsdev/FieldWorks/blob/8c87915626ccd44eecbb2e2acef2c981fc7a48d9/Src/xWorks/WebonaryLogViewer.cs#L60)):*
> ```Smalltalk
> 			{
> 				// Read and deserialize JSON from file
> 				foreach (var line in File.ReadLines(filePath))
> ```

Should we remove the if statement from inside the loop?



_Code snippet:_
```Smalltalk
var nonEmptyLines = File.ReadLines(filePath)
                         .Where(line => !string.IsNullOrWhiteSpace(line));

foreach (var line in nonEmptyLines)
{
    try
    {
        var entry = JsonConvert.DeserializeObject<UploadLogEntry>(line);
        _logEntries.Add(entry);
    }
    catch (JsonException ex)
    {
        Console.WriteLine($"Error deserializing line: {ex.Message}");
    }
}
```


<!-- Sent from Reviewable.io -->

2024-10-29 20:31 UTC, jasonleenaylor reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/187)* status: 0 of 13 files reviewed, 3 unresolved discussions (waiting on @hahn-kev and @JakeOliver28)

___
*[`Src/xWorks/UploadToWebonaryDlg.cs` line 331 at r2](https://reviewable.io/reviews/sillsdev/FieldWorks/187#gh-1820001988:-OAOxqEQAPPrfvQbPJ32:bniox6d) ([raw file](https://github.com/sillsdev/FieldWorks/blob/3765fdab76d55f3cf307a80356f0f1a0786f39a9/Src/xWorks/UploadToWebonaryDlg.cs#L331)):*
<details><summary><i>Previously, hahn-kev (Kevin Hahn) wrote…</i></summary><blockquote>

why the call `Enum.ToObject` instead of just casting the result of Math.Max directly to the enum? I can't see any functional difference
</blockquote></details>

No good reason apparently.
___
*[`Src/xWorks/WebonaryLogViewer.cs` line 60 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/187#-OAO-7-Y6Q3_1xOEDrVu:-OAOyXr5B8Kxd03M97Ii:b-896fix) ([raw file](https://github.com/sillsdev/FieldWorks/blob/8c87915626ccd44eecbb2e2acef2c981fc7a48d9/Src/xWorks/WebonaryLogViewer.cs#L60)):*
<details><summary><i>Previously, JakeOliver28 (Jake Oliver) wrote…</i></summary><blockquote>

Should we remove the if statement from inside the loop?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-30 15:41 UTC, JakeOliver28 commented
> > _[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/187)_ status: 0 of 13 files reviewed, 3 unresolved discussions (waiting on @hahn-kev and @JakeOliver28)
> 
> _[`Src/xWorks/UploadToWebonaryDlg.cs` line 331 at r2](https://reviewable.io/reviews/sillsdev/FieldWorks/187#gh-1820001988:-OAOxqEQAPPrfvQbPJ32:bniox6d) ([raw file](https://github.com/sillsdev/FieldWorks/blob/3765fdab76d55f3cf307a80356f0f1a0786f39a9/Src/xWorks/UploadToWebonaryDlg.cs#L331)):_
> 
> Previously, hahn-kev (Kevin Hahn) wrote…
> No good reason apparently.
> 
> _[`Src/xWorks/WebonaryLogViewer.cs` line 60 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/187#-OAO-7-Y6Q3_1xOEDrVu:-OAOyXr5B8Kxd03M97Ii:b-896fix) ([raw file](https://github.com/sillsdev/FieldWorks/blob/8c87915626ccd44eecbb2e2acef2c981fc7a48d9/Src/xWorks/WebonaryLogViewer.cs#L60)):_
> 
> Previously, JakeOliver28 (Jake Oliver) wrote…
> Done.

Were this change and the other change committed?

2024-10-30 17:43 UTC, jasonleenaylor commented
*[`Src/xWorks/WebonaryLogViewer.cs` line 60 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/187#-OAO-7-Y6Q3_1xOEDrVu:-OATWPIAA-1t89HUwEBM:b-q85ttn) ([raw file](https://github.com/sillsdev/FieldWorks/blob/8c87915626ccd44eecbb2e2acef2c981fc7a48d9/Src/xWorks/WebonaryLogViewer.cs#L60)):*
<details><summary><i>Previously, JakeOliver28 (Jake Oliver) wrote…</i></summary><blockquote>

Were this change and the other change committed?
</blockquote></details>

Hmm, apparently not. They are now! :thumbsup: 


<!-- Sent from Reviewable.io -->

2024-10-30 18:05 UTC, JakeOliver28 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/187#-:-OATa_eoAJoFanXZjCfC:bnfp4nl)* status: 0 of 13 files reviewed, 3 unresolved discussions (waiting on @hahn-kev)



<!-- Sent from Reviewable.io -->

2024-10-30 21:36 UTC, merged